### ISSUE TITLE
About the evaluation result (detection rate) in the paper.

### ISSUE THREAD

**Issue by wakananai** [cs-chan/Exclusively-Dark-Image-Dataset#12]
Hi, 
Thanks for sharing paper, code and dataset to public. Since I'm doing some experiment on your dataset and want to compare the evaluation results with yours. I wonder that what is the "detection rate" mean in paper Section 4. Does it mean "precision" under common object detection scenario? Would you please provide mean average precision(mAP) of the object detection evaluation result or  tell how to derive mAP from the scores in the paper?

Thanks a lot.

**Comment by yploh** [comment]
Hello,
Thank you for your interest in using our dataset.

There is a point that must be noted for the evaluations in the work: 
Object proposal algorithms are used, instead of object detection models. Therefore, proposal algorithms will give more bounding boxes likely to contain objects as compared to actual object detection by a model.

So, to answer your questions:
1. Yes, detection rate can be likened to "precision", i.e. among all the proposed bounding boxes, how likely they contain an annotated object. However, we do not use precision as to not mislead the actual common object detection model evaluation which includes the object class.
2. Taking note of the difference between object proposal and object detection as mentioned above, we do not provide the mAP.
3. In order to properly perform mAP evaluation on the data, object detection models such as Faster-RCNN, YOLOv3, etc. should be applied to perform the detection instead of just deriving from the proposal results we provided.

Hope this clarification is helpful for your work.

**Comment by wakananai** [comment]
Thank you for your reply and information. It seems that I confuse object proposal with detection.
